algoritmo "Estoquemedio"
// Função :
// Autor :
// Data : 10/08/2023
// Seção de Declarações 
var
   pmin, pmax, media : real
inicio
// Seção de Comandos
   escreval("Calculadora de Estoque Médio de uma peça")
   escreval("Digite a Quantidade de Produto Minimo")
   leia(pmin)
   escreval("Digite a Quantidade de Produto Maxima")
   leia(pmax)
//Calcular
          media <-(pmin+pmax)/2
          escreval("a media é",media)

fimalgoritmo
