algoritmo "semnome"
// Função :
// Autor :
// Data : 10/08/2023
// Seção de Declarações
var
   p1, p2, p3, p4, media: real
inicio
// Seção de Comandos 
   escreval("Calcula média final")
   escreval("Insira a nota de p1")
   leia(p1)
   escreval("Insira a nota de p2")
   leia(p2)
   escreval("Insira a nota de p3")
   leia(p3)
   escreval("Insira a nota de p4")
   leia(p4)
   //calcula a media
   media <-(p1+p2+p3+p4)/4
   escreval("O resultado da media final das provas é", media)
fimalgoritmo
